"""Creates tables in pizza_restaurant_db 

Revision ID: 570bb53676ad
Revises: 
Create Date: 2025-06-15 14:53:46.404328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570bb53676ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantpizzas', schema=None) as batch_op:
        batch_op.drop_constraint('restaurantpizzas_restaurant_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('restaurantpizzas_pizza_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantpizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('restaurantpizzas_pizza_id_fkey', 'pizzas', ['pizza_id'], ['id'])
        batch_op.create_foreign_key('restaurantpizzas_restaurant_id_fkey', 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###
